# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build_and_export do
    gym(workspace: "CatsAndModules_KaterynaAvramenko.xcworkspace")
    firebase_app_distribution(
      release_notes: "Release note 1",
      testers: "kavramenko2000@gmail.com, n.marhal@ukma.edu.ua"
    )
end

lane :take_screenshots do
      snapshot
  end
end